name: CI

on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1.3.0
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args:
            --all -- --check
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1.3.0
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: cargo nextest
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --no-fail-fast
      - name: cargo doctest
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc

  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri
      - uses: Swatinem/rust-cache@v1.3.0
      - run: cargo miri setup
      - name: cargo miri test
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test --no-fail-fast
